Cray-HPE/metal-init

bin/bios-baseline.sh
This script had 2&>1 instead of 2>&1, causing a file named `1`
to be created on every invocation.  Additionally, 2>&1 is technically
supposed to be the last thing in the statement.
- Fixes CASMINST-3639
=> CASMINST-3639: fix bash syntax error

bin/csi-setup-lan0.sh
Update to line 23 to replace wicked ifreload lan0 with wicked ifdown lan0 && wicked ifup lan0. Wicked by default looks at its /etc/wicked/common.xml to determine if there has been a change. If someone runs this script with invalid values, then re-runs it, wicked doens't see anything changed in common.xml, so it doesn't actually reload the interfaces. There doesn't seem seem to be a force flag option but this changed worked in vale in casminst-4061 to resolve the issue.
- Fixes #CASMINST-4061
- Docs Pull Request
modifies init script to use wicked ifdown/ifup instead of wicked reload to make the script repeatable/idempotent.
done
What is less risky, or more risky now - or if your mod fails is there a new risk?
=> CASMINST-4061 change wicked ifreload to down and up

bin/metalid.sh
- Relates to: CASMINST-4909
`canu` is now included in the `metalid.sh` output.
```bash
= PIT Identification = COPY/CUT START =======================================
VERSION=1.8.0
TIMESTAMP=20220628162838
HASH=ge005460
CRAY-Site-Init build signature...
Build Commit   : caa0690373e6c58b0cd2eff0c9332b182ed27712-heads-v1.20.0
Build Time     : 2022-06-24T23:17:09Z
Go Version     : go1.18
Git Version    : v1.20.0
Platform       : linux/amd64
App. Version   : ..
canu-1.6.5-1.x86_64
ilorest-3.5.1-1.x86_64
metal-basecamp-1.2.0-1.x86_64
metal-ipxe-2.2.7-1~mtl_1657_add_var_to_track_dhcp_nic~20220531135656.8f13925.noarch
metal-net-scripts-0.0.2-1.noarch
pit-init-1.2.29~1~g3c8ffa7-1.noarch
pit-nexus-1.1.4-1.x86_64
= PIT Identification = COPY/CUT END …
```
=> CASMINST-4909 Include canu in the rpm output

Jenkinsfile.github
- Docs Pull Request
`main` should not be building stable since we build on git-tags. The main stables have been around for a little bit and have produced these oddball RPMs:
I'm not sure why there's duplicate RPMs, but both the ones with and without the `~` will cease being created with this PR.
I've cleaned up Artifactory prior to making this PR, so those RPMs in this picture with the HASH are no longer there.
=> Without .version main shouldn't build stable

bin/set-sqfs-links.sh
- Fixes: CASMINST-5003
This PR does two things:
1. It implements CASMINST-5003 which will update `script.ipxe` to tell dracut to download the artifacts into a directory named after `CSM_RELEASE` (e.g. `/run/initramfs/live/$CSM_RELEASE`). If `CSM_RELEASE` is not set, then the default directory is used (e.g. `/run/initramfs/live/LiveOS`). This is controlled by setting the `rd.live.dir` argument on the kernel commandline.
2. This tidies the output of the script up and adds some error checking
- Instead of sleeping for 2 seconds after setting the BMCs to DHCP, the number of actual BMCs that have DHCPed is checked against an expected number. The current count will print into the screen until the actual DHCP BMC count meets the expected number of BMCs.
- Instead of printing …
=> CASMINST-5003

bin/set-sqfs-links.sh
- Fixes: MTL-1868
Removes the redundant printing message "Waiting on 9 to request DHCP ..." seen in the below snippet. Instead it'll be printed once, and then the counter is printed until the number of actuals meets the number of expected.
```bash
redbull-ncn-m001-pit:~ # set-sqfs-links.sh
Resolving images to boot ...
Images resolved
Kubernetes Boot Selection:
kernel: /var/www/ephemeral/data/k8s/fe775c6-1659395320990/5.3.18-150300.59.76-default-fe775c6-1659395320990.kernel
initrd: /var/www/ephemeral/data/k8s/fe775c6-1659395320990/initrd.img-fe775c6-1659395320990.xz
squash: /var/www/ephemeral/data/k8s/fe775c6-1659395320990/secure-kubernetes-fe775c6-1659395320990.squashfs
Storage Boot Selection:
kernel: /var/www/ephemeral/data/ceph/fe775c6-1659395320990/5.3.18-150300.59 …
```
=> MTL-1868 Remove redundant print

bin/get-sqfs.sh
Adds progress bars to get-sqfs.sh script
- Fixes: The ability to know if you can make coffee with an eta on each download
- Requires:
- Relates to:
Bug/feature/ish fix
- Docs Pull Request
- [ x] I tested this on internal system redbull
n/a
n/a just outputs progress bar messages
=> CASMINST-5209: Add progress bars to wget invocations

bin/set-sqfs-links.sh
- Fixes: MTL-1876
- Relates to: CASMINST-4849
To align to what CFS uses, and to make the entire boot process the same for bootstrap, runtime, and customized images (CFS/IMS), we'll use `rootfs` as the filename instead of `filesystem.squashfs`. This will prevent us from needing to fiddle the `rd.live.squashimg` parameter at various points of an install or upgrade.
=> MTL-1876 Use `rootfs`

bin/pit-init.sh
- Fixes: MTL-1953
Fixes incorrect variable usage, preventing an override of `PITDATA` when no partition is used.
=> MTL-1953 Refactor `PIT_DATA` to `PITDATA`

bin/csi-setup-lan0.sh
- Fixes: MTL-1952
Only 1 `DNS` can be defined, unless it uses quotes. Device(s) go last.
=> MTL-1952 Fix `csi-setup-lan0.sh` usage

bin/get-sqfs.sh
With the addition of the 'oval' files, wget wants to read and follow every URL therein. To avoid this, replace `--mirror` with the equivalent command, but only at depth == 1 vs depth == inf.
- Fixes: MTL-1975
=> MTL-1975: don't recursively follow links

bin/csi-setup-lan0.sh
The pit isn't really m001, so stop pretending it is.
- Fixes: CASMTRIAGE-4671 CASMTRIAGE-4672
=> CASMTRIAGE-4671 CASMTRIAGE-4672: nix the ncn-m001 hardcode

bin/pit-init.sh
CASMMON-208: Automate prometheus, grok exporter and grafana gets instantiated automatically on Combined Install Media LiveDVD
_Summarize what has changed. Explain why this PR is necessary. What is impacted? Is this a new feature, critical bug fix, etc?_
_Is this change backwards incompatible, backwards compatible, or a backwards compatible bugfix?_
_List and characterize relationship to Jira/Github issues and other pull requests. Be sure to list dependencies._
* Resolves - https://jira-pro.its.hpecorp.net:8443/browse/CASMMON-208
_List the environments in which these changes were tested._
Gamora-csm-pit
gamora-ncn-m001-pit: # podman ps
CONTAINER ID  IMAGE                                                                                   COMMAND               CREATED        STATUS …
=> CASMMON-208: Automate prometheus, grok exporter and grafana gets instantiated automatically on PIT node.

bin/metalid.sh, bin/pit-init.sh
- Fixes: CASMMON-250
- Requires: https://github.com/Cray-HPE/pit-observability/pull/5
- Relates to: #62 #60 
Do not `restart` the services, they operate with better success if they're `start`ed. This stops them for consistency, and then enables and starts them in one call.
=> CASMMON-250 pit-observability

bin/pit-init.sh
- Relates to: CASMMON-250 #63 #64 
Time each service, provide a heads-up that this may take a while, and suppress the `systemctl` output.
=> CASMMON-250 Prettify the output

bin/pit-init.sh, bin/set-sqfs-links.sh
- Fixes: MTL-2080
The `rootfs` and `kernel` files search by suffix and in doing so they do not accidentally select `sha256` sum files.
The `initrd` searches by prefix because the suffix could change in the future (if we change compression or format). Since it searches by prefix the search picks up the `sha256` sums. This change will ensure those are excluded.
=> MTL-2080 Ignore `sha256sum` `initrd` files

bin/set-sqfs-links.sh
=> CASMINST-6418: make sure we find an initrd, not an initrd sha file

Jenkinsfile.github, bin/pit-init.sh
- Fixes: MTL-2000
- Relates to: MTL-2032
`csi patch packages` is a new command from MTL-2000 that will patch a given `cloud-init.yaml` file into `data.json`. The intention here is that `cloud-init.yaml` contains a list of `repos` and `packages` that we want cloud-init to install when it runs on the deployed nodes.
If the `cloud-init.yaml` file does not exist in the tar ball, and none is provided on the command line, then this step is skipped. Additionally, if `csi patch packages` is not available then the step is skipped.
Lastly this adds some skip options and a usage for `pit-init.sh`.
If the installed version of `cray-site-init` does not have `csi patch packages` the script will continue with an info message:
```
The installed version of CSI does not have the `csi …
```
=> MTL-2000 Invoke `csi patch packages`

bin/pit-init.sh
- Fixes: CASMINST-6525
`CSM_RELEASE` was used without prepending the `csm-` prefix, causing a failure when resolving the tar ball.
=> CASMINST-6625 Fix `CSM_RELEASE`

bin/get-sqfs.sh
Switch to using `curl` for downloading the Hypervisor ISO (since we don't need to pull more than 1 artifact from its directory anymore), management-vm and kubernetes-vm.
`wget` is not availabvle on the hypervisor, if a developer uses metal-init as a shortcut then it'll flop when downloading fawkes artifacts.
=> MTL-2198 ISO and QCOW2

bin/get-sqfs.sh
- Fixes: ARM downloads, and general downloads
- Docs Pull Request
- ARM64 machines were not resolving the right image artifact names for download, resulting in `404`
- Every image `base_url` was missing the `repository` except for storage-ceph, causing `404` errors
=> Arm64 support

bin/pit-init.sh
- Fixes: CASMINST-6859
Call to `load_packages()` function was located inside condition, which only applies it to non GCP systems. This call is also needed in vShasta.
Ran `pit-init.sh` twice on vShasta system. Ensured successful script execution and checked output from `load_packages` function:
Using cloud-init.yaml from the CSM release tarball: /var/www/ephemeral/csm-1.5.1-rc.3/rpm/cloud-init.yaml
2024/05/03 20:12:49 Patched cloud-init seed data in place
Low risk - only changes behavior in a block specific to vShasta.
=> CASMINST-6859 pit-init.sh is skipping load_packages on vShasta

bin/csi-pxe-bond0.sh, bin/csi-pxe-hmn.sh
- Fixes: MTL-2554 (CAST-37780)
The DNSMasq files generated by `csi-pxe-bond0.sh` and `csi-pxe-hmn.sh` are conflicting with generated files from the CSM installation.
These scripts are invoked as part of a fresh install operation for collecting MAC addresses, and therefore are not part of a reinstallation (where MAC addresses are already known). The scripts may also be ran after hardawre changes.
The files generated by these scripts are intended to be replaced by the CSM pre-installation. When `pit-init.sh` is invoked, new `MTL.conf` and `HMN.conf` files are created and copied into `/etc/dnsmasq.d`.
These files can not coexist with the generated files from `pit-init.sh` as they contain conflicting parameters.
This change modifies the casing on the file names, allowing …
=> MTL-2554 Uppercase DNSMasq files
